name       : haskell-blaze-markup
version    : 0.8.2.1
release    : 2
source     :
    - https://hackage.haskell.org/package/blaze-markup-0.8.2.1/blaze-markup-0.8.2.1.tar.gz : 90ab7cbc29df9fbe24e208ade58ca9828e3074f1163618f1faaf4da8f0600146
license    : BSD-3-Clause
component  : programming.haskell
summary    : Core modules of a blazingly fast markup combinator library for the Haskell programming language.
description: |
    Core modules of a blazingly fast markup combinator library for the Haskell programming language.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
