name       : haskell-blaze-markup
version    : 0.8.0.0
release    : 1
source     :
    - http://hackage.haskell.org/package/blaze-markup-0.8.0.0/blaze-markup-0.8.0.0.tar.gz : 19e1cbb9303803273ed7f9fcf3b8b6938578afbed2bfafe5ea9fcc6d743f540f
license    : BSD-3-Clause
component  : programming.haskell
summary    : Core modules of a blazingly fast markup combinator library for the Haskell programming language.
description: |
    Core modules of a blazingly fast markup combinator library for the Haskell programming language.
builddeps  :
    - haskell-blaze-builder
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
