name       : haskell-blaze-markup
version    : 0.8.2.5
release    : 3
source     :
    - https://hackage.haskell.org/package/blaze-markup-0.8.2.5/blaze-markup-0.8.2.5.tar.gz : 1bd3ba68775e4a11efc71567e30e8ef3d27801c6b5fe4a1abf57dd747af37661
license    : BSD-3-Clause
component  : programming.haskell
summary    : Core modules of a blazingly fast markup combinator library for the Haskell programming language.
description: |
    Core modules of a blazingly fast markup combinator library for the Haskell programming language.
builddeps  :
    - haskell-blaze-builder-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - haskell-blaze-builder-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
